//title:	Example MMD Document 1
//author:	

#Example MMD Document 1

The purpose of this series is to show what all M-Markdown strives to do;
to show good M-Markdown, etc.
But this first document is to demonstrate that M-Markdown is fully compatible with normal Markdown, despite it's different purpose intent
(to be on easy-to-learn, simple typesetting markup language;
perhaps even a simplistic front end for more traditionals, like LaTeX or some Roff implementations.)


##Formatting

The most important types of formatting in Markdown (MD) your inline formatting and blocks quotes.
After that, are your code blocks, embedded links, and headings.
Though, because MD was made as a front-end HTML, it was _**never**_ intended for extensive formatting options---%
rather, it was relies on CSS to determine those things.

  Extending MD is rather controversial in my own mind.
I have opted to eliminate any felt redundancy, and extend where necessary, such as options for setting page size and the like, if compiled.

*italics*
***BI***
_*IU*_
_~*IUS*~_
~*IS*~

**Bold**
_**BU**_
_~**BUS**~_
~**BS**~

~Strike~

_Underline_
_~US~_

_***All***_
_~***ALL+***~_



###Heading 3

####Heading 4

#####Heading 5

######Heading 6
