//title:	Example MMD Document 1
//author:	

#Example MMD Document 1

The purpose of this series is to show what all M-Markdown strives to do.
To show good M-Markdown, etc.
But this first document is to demonstrate that M-Markdown is fully compatible with normal Markdown.
But, it will highlight what may be confusingly different.


##Formatting

M-Markdown preserves most things from normal markdown,
but some things have changed decently.

`Inline code`, *Italics*, **bold**, are mostly the same, with the exception of using underscores (\_) in place of asterisks (\*).
This introduces _underlining_, which some variants of Markdown and Markdown-inspired markup languages (like Fountain) have implemented. /* */

###Heading 3

####Heading 4

#####Heading 5

######Heading 6
