//title:     M-Markdown Example Document 2
//author:    Matþew T. Scarbrough
//document:  Article
//draftdate: May 15, 2020

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

M-Markdown Example 2
====================

/* Consider writing document showing text alignment */

This document aims to show what M-Markdown (MMD) can be,
as well as layout a base standard for what a *“good”* MMD document _might_ look like.


 Goals
 -----

MMD aspires to be a simple, pre-processor-reliant, markup language, used for writing,
as well as for an easy-to-read, *Markdown* option for notetaking.
As of right now, using it (in Vim) for notetaking is accomplished,
so the next big milestone will be to make a simple compiler for DjVu,
or to convert the text into a simple, eye-pleasing Roff file that can then be compiled into a proper PDF

  Ideally, a good compiler would be lightweight and able to handle PDF _**AND**_ DjVu.
Also, it should have some predetermined layouts, such as *article*, *novel manuscript*, *MLA*, *Chicago*, *screenplay*, etc.

  So, at a glance:

+ Create Syntax files
  - Vim (done)
  - Gedit
  - Emacs        //low priörity, due to Org Mode
+ Working on compilers
  - First party compiler
    1. DjVu
    2. PDF
    3. LaTeX     //nicer front-end, for those who know what they want
    4. GNU Roff  //ditto


  Language Selection
  ~~~~~~~~~~~~~~~~~~

Ideally, a compiler should be written in something fast, like C or Go, but, if possible, a simple POSIX shell script for \*NIX systems is a nice idea, for nothing that contains pictures, etc.

  As of right now, I am currently learning Rust and want the experience doing that myself, and need the coding experienc, so it is probably going to be a while,
but the major purpose of MMD is finished---//
an MD-based markup language for note taking, for use in a plain text editor, like Vim.


 Conclusion
 ----------

If you like it, thank you---I am glad to see that I am not the only one who has wanted something like this!
